{% set name = "httpx-ntlm" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/httpx_ntlm-{{ version }}.tar.gz
  sha256: 41be8a2ba85143484e617dcb917d4b19e3ae12afdc688622a4901034993b53e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - httpx >=0.24
    - pyspnego >=0.3

test:
  imports:
    - httpx_ntlm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ulodciv/httpx-ntlm
  summary: This package allows for HTTP NTLM authentication using the HTTPX library.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
